language: python
python:
 - "3.5"
install:
 - pip install -r requirements.txt
git:
  depth: 50
before_install:
 - chmod +x test/test_view.py
jobs:
  include:
  - name: "project-1"
    python: "3.5"
script: python -m pytest
