language: python
python:
 - "3.5"
install:
 - pip install -r requirements.txt
git:
  depth: 50
jobs:
  include:
  - name: "project-1"
    python: "3.5"
#    env: 
#     - TEST_SUITE1=3
#     - TEST_SUITE2=4
#script: python -m pytest
script: test/test_code.py
