language:
  python
python:
 - "3.5"
install:
 - pip install -r requirements.txt
 - pip install coverage
git:
  depth: 50
jobs:
  include:
  - name: "project-1"
    python: "3.5"
script:
  - coverage run -m pytest -q --flake8 test/test_class.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
